<script lang="ts">
    import type {WizardStateStore} from "./wizardState";
    import {
        applyJsonSchema,
        displayOptions,
        generateJsonSchema,
        startApiCreation,
        startJsonImprovement
    } from "./wizardState";
    import type {JsonSchema} from "@cozemble/model-core";
    import type {Writable} from "svelte/store";
    import {json} from "../fromDocument/partialJson";

    export let wizardState: WizardStateStore
    export let jsonSchema: Writable<JsonSchema | null>

    function jsonMeetsNeeds() {
        $wizardState = startApiCreation
    }

    function jsonNeedsImprovement() {
        $wizardState = startJsonImprovement
    }

    function onApplyJsonSchema() {
        $wizardState = applyJsonSchema
    }

    function markSections() {
        alert("Not implemented yet")
    }

    function changeTables() {
        alert("Not implemented yet")
    }

    function onEditJsonSchema() {
        alert("Not implemented yet")
    }

    function onGenerateJsonSchema() {
        $wizardState = generateJsonSchema
    }
</script>

{#if $wizardState._type === 'generatingFirstJson'}
    <div class="flex flex-col items-center">
        <h3>Generating our first guess at the json output...</h3>
        <h4>This is probably going to be a really bad guess, but we can improve it.</h4>
    </div>
{/if}
{#if $wizardState._type === 'explainingFirstJson'}
    <div class="flex flex-col items-center">
        <h3>This JSON was generated by AI without any context</h3>
        <h4>We can make it better, but first of all, can you tell me whether this JSON:</h4>
        <div class="mt-2 flex">
            <button class="btn btn-secondary btn-sm" on:click={jsonMeetsNeeds}>meets your needs</button>
            <div class="ml-2 mr-2">or</div>
            <button class="btn btn-secondary btn-sm" on:click={jsonNeedsImprovement}>needs improvement</button>
        </div>
    </div>
{/if}
{#if $wizardState._type === 'startApiCreation'}
    <div class="flex flex-col items-center">
        <h3>API Creation - coming soon</h3>
    </div>
{/if}
{#if $wizardState._type === 'startJsonImprovement'}
    <div class="flex flex-col items-center">
        <h3>Let's improve this JSON</h3>
        <h4>We have a choice of tools you can use</h4>
        <div class="mt-4 flex">
            <div class="card w-96 bg-base-100 shadow-xl border">
                <div class="card-body">
                    <h2 class="card-title">Apply a json schema</h2>
                    <p>Helps the AI figure out what you want from the document</p>
                    <div class="card-actions justify-end">
                        <button class="btn btn-secondary btn-sm" on:click={onApplyJsonSchema}>Apply Schema</button>
                    </div>
                </div>
            </div>
            <div class="card w-96 bg-base-100 shadow-xl ml-4 border">
                <div class="card-body">
                    <h2 class="card-title">Mark sections in the document</h2>
                    <p>Helps the AI identify "logical" data sections in the document</p>
                    <div class="card-actions justify-end">
                        <button class="btn btn-secondary btn-sm" on:click={applyJsonSchema}>Mark Sections</button>
                    </div>
                </div>
            </div>
            <div class="card w-96 bg-base-100 shadow-xl ml-4 border">
                <div class="card-body">
                    <h2 class="card-title">Make changes to tables</h2>
                    <p>Merge tables, extract/delete rows, apply data formats to rows and cells, etc</p>
                    <div class="card-actions justify-end">
                        <button class="btn btn-secondary btn-sm" on:click={changeTables}>Change Tables</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-4"><em>You can use these tools individually or in combination</em></div>
    </div>
{/if}
{#if $wizardState._type === 'applyJsonSchema'}
    {#if $jsonSchema === null}
        <div class="flex flex-col items-center">
            <h3>Apply a json schema</h3>
            <h4>You can choose how to apply a json schema</h4>
            <div class="mt-4 flex">
                <div class="card w-96 bg-base-100 shadow-xl border">
                    <div class="card-body">
                        <h2 class="card-title">Supply your own JSON Schema</h2>
                        <p>If you already have a JSON schema, you can paste it in</p>
                        <div class="card-actions justify-end">
                            <button class="btn btn-secondary btn-sm" on:click={onEditJsonSchema}>Paste Schema</button>
                        </div>
                    </div>
                </div>
                <div class="card w-96 bg-base-100 shadow-xl ml-4 border">
                    <div class="card-body">
                        <h2 class="card-title">Generate a JSON Schema</h2>
                        <p>We can use AI to generate an initial schema, and then you can tweak it</p>
                        <div class="card-actions justify-end">
                            <button class="btn btn-secondary btn-sm" on:click={onGenerateJsonSchema}>Generate Schema
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {:else}
        <div class="flex flex-col items-center">
            <h3>Edit existing json schema = to do</h3>
        </div>
    {/if}
{/if}
{#if $wizardState._type === "generateJsonSchema"}
    <div class="flex flex-col items-center">
        <h3>Generating a JSON schema</h3>
        <h4>This is using GPT-4, because GPT-3.5 does a bad job at this, so it is a bit slow</h4>
    </div>
{/if}
{#if $wizardState._type === displayOptions._type}
    <div class="flex flex-col items-center">
        <h3>We can improve this JSON further</h3>
        <h4>We have a choice of tools you can use</h4>
        <div class="mt-4 flex">
            {#if $jsonSchema === null}
            <div class="card w-96 bg-base-100 shadow-xl border">
                <div class="card-body">
                    <h2 class="card-title">Apply a json schema</h2>
                    <p>Helps the AI figure out what you want from the document</p>
                    <div class="card-actions justify-end">
                        <button class="btn btn-secondary btn-sm" on:click={onApplyJsonSchema}>Apply Schema</button>
                    </div>
                </div>
            </div>
                {/if}
            <div class="card w-96 bg-base-100 shadow-xl ml-4 border">
                <div class="card-body">
                    <h2 class="card-title">Mark sections in the document</h2>
                    <p>Helps the AI identify "logical" data sections in the document</p>
                    <div class="card-actions justify-end">
                        <button class="btn btn-secondary btn-sm" on:click={applyJsonSchema}>Mark Sections</button>
                    </div>
                </div>
            </div>
            <div class="card w-96 bg-base-100 shadow-xl ml-4 border">
                <div class="card-body">
                    <h2 class="card-title">Make changes to tables</h2>
                    <p>Merge tables, extract/delete rows, apply data formats to rows and cells, etc</p>
                    <div class="card-actions justify-end">
                        <button class="btn btn-secondary btn-sm" on:click={changeTables}>Change Tables</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{/if}
