describe('data table', () => {
  it('supports building a simple customer and bookings database', () => {
    cy.visit('http://localhost:5173/empty')
    cy.get('.add-table-link').click()
    cy.get('.table-name').type('{selectall}Customers{enter}')
    cy.get('.edit-field-1').click()
    cy.get('input.property-name').type('{selectall}First name')
    cy.get('input.required-toggle').click()
    cy.get('button.save-property').click()
    cy.get('.add-field').click()
    cy.get('input.property-name').type('{selectall}Last name{enter}')
    cy.get('.add-field').click()
    cy.get('input.property-name').type('{selectall}Email')
    cy.get('input.required-toggle').click()
    cy.get('input.unique-toggle').click()
    cy.get('button.save-property').click()
    cy.get('.add-field').click()
    cy.get('input.property-name').type('{selectall}Phone')
    cy.get('input.required-toggle').click()
    cy.get('input.unique-toggle').click()
    cy.get('button.save-property').click()

    cy.get('button.add-record').click()
    cy.focused().type('John').realPress('Tab')
    cy.focused().type('Smith').realPress('Tab')
    cy.focused().type('john@email.com').realPress('Tab')
    cy.focused().type('+44 7777 333444')
    cy.get('button.save-record').click()

    cy.get('button.add-record').click()
    cy.focused().type('Jane').realPress('Tab')
    cy.focused().type('Smith').realPress('Tab')
    cy.focused().type('jane@email.com').realPress('Tab')
    cy.focused().type('+44 8888 444555')
    cy.get('button.save-record').click()

    cy.get('.add-table-link').click()
    cy.get('.table-name').type('{selectall}Bookings{enter}')
    cy.get('.edit-field-1').click()
    cy.get('input.property-name').type('{selectall}Customer')
    cy.get('select.property-type').select('Link to another record')
    cy.get('select.referenced-model').select('Customers')
    cy.get('button.save-property').click()

    cy.get('.add-field').click()
    cy.get('input.property-name').type('{selectall}Date')
    cy.get('select.property-type').select('Date')
    cy.get('input.required-toggle').click()
    cy.get('button.save-property').click()

    cy.get('.add-field').click()
    cy.get('input.property-name').type('{selectall}Notes')
    cy.get('input.multiline-toggle').click()
    cy.get('button.save-property').click()

    cy.get('button.add-record').click()
    cy.focused().realPress('Enter')
    cy.contains('First name').click()
    cy.contains('Last name').click()
    cy.get('button.save-view').click()
    cy.get('select.reference-selector').select('Jane Smith').realPress('Tab')
    cy.get('input.date-input').type('2023-11-20').realPress('Enter')
    cy.get('button.save-record').click()

    cy.get('button.add-sub-section').click()
    cy.contains('Next').click()
    cy.contains('Next').click()
    cy.focused().type('{selectall}Bike{enter}')

    cy.get('.edit-field-1').eq(1).click()
    cy.get('input.property-name').type('{selectall}Make')
    cy.get('input.required-toggle').click()
    cy.get('button.save-property').click()

    cy.get('.add-field').eq(1).click()
    cy.get('input.property-name').type('{selectall}Model')
    cy.get('input.required-toggle').click()
    cy.get('button.save-property').click()

    cy.get('.add-field').eq(1).click()
    cy.get('input.property-name').type('{selectall}Pictures')
    cy.get('select.property-type').select('Attachment')
    cy.get('button.save-property').click()
  })
})
